#ifndef MOUSEBUTTONCODES_H
#define MOUSEBUTTONCODES_H

#define PROTEA_MOUSE_BUTTON_1         0
#define PROTEA_MOUSE_BUTTON_2         1
#define PROTEA_MOUSE_BUTTON_3         2
#define PROTEA_MOUSE_BUTTON_4         3
#define PROTEA_MOUSE_BUTTON_5         4
#define PROTEA_MOUSE_BUTTON_6         5
#define PROTEA_MOUSE_BUTTON_7         6
#define PROTEA_MOUSE_BUTTON_8         7
#define PROTEA_MOUSE_BUTTON_LAST      PROTEA_MOUSE_BUTTON_8
#define PROTEA_MOUSE_BUTTON_LEFT      PROTEA_MOUSE_BUTTON_1
#define PROTEA_MOUSE_BUTTON_RIGHT     PROTEA_MOUSE_BUTTON_2
#define PROTEA_MOUSE_BUTTON_MIDDLE    PROTEA_MOUSE_BUTTON_3

#endif //MOUSEBUTTONCODES_H
